Update replies.go
ImpactDevelopment/ImpactBot pull request #99
Opened 2020-08-10 02:05 UTC by DoctorBang

Nice gif for 1.16, as well as the download for Legacy versions of Impact.

2020-08-14 15:25 UTC, LeafHacker requested changes
Not sure about this

2020-08-14 15:25 UTC, LeafHacker commented on replies.go
> +		message: "Impact for older versions is no longer availible to comply with Mojang's EULA. You can still download them from: https://snorlax.cc/impact.html",
We cannot provide or condone illegally distributions of Minecraft/optifine/old-impact.

2020-08-14 15:25 UTC, LeafHacker commented on replies.go
>  	},
I wonder if using `![alt text](image URL)` syntax is better? At the very least a descriptive link is better than just pasting a massive URL into the message.

Perhaps the better solution is to add a way for bot replies to have an image attached, this wouldn't be particularly complex.

2020-08-14 20:54 UTC, DoctorBang commented
Honestly this PR was for the meme. And if you looked at the link, you'd see that the link to Impact 1.8 was a rick-roll Leaf.

2020-08-15 22:21 UTC, LeafHacker commented
lmao

2020-09-06 11:36 UTC, closed without merging